platform: linux

image_resource:
  type: registry-image
  source:
    repository: quay.io/tiran/cpythonbuild
    tag: emsdk3

inputs:
- name: repo

run:
  path: python3
  args:
    - repo/Tools/wasm/wasm_build.py
    - ((target))
    - build
