platform: linux

image_resource:
  type: registry-image
  source:
    repository: quay.io/tiran/cpythonbuild
    tag: emsdk3

inputs:
- name: repo

params:
  ACTION: build

run:
  path: python3
  args:
    - Tools/wasm/wasm_build.py
    - ((target))
    - $ACTION
  dir: repo
