platform: linux

image_resource:
  type: registry-image
  source:
    repository: quay.io/tiran/cpythonbuild
    tag: emsdk3

inputs:
- name: repo

outputs:
- name: builddir
  path: repo/builddir/((target))

params:
  ACTION: build
  EM_CONFIG: /emsdk

run:
  path: sh
  args:
    - -c
    - python3 Tools/wasm/wasm_build.py ((target)) $ACTION
  dir: repo
