platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: alpine

inputs:
- name: path

outputs:
- name: ((name)).zip

run:
  path: sh
  args:
    - -c
    - python3 -m zipfile --create ((name)).zip path/*
